apiVersion: v1
kind: Namespace
metadata:
  name: data-pipeline
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-quota
  namespace: data-pipeline
spec:
  hard:
    requests.cpu: "10"
    requests.memory: 20Gi
    limits.cpu: "20"
    limits.memory: 30Gi
    persistentvolumeclaims: "10"